{% set name = "ironflow" %}
{% set version = "0.0.4" %}
{% set sha256 = "c742d4c604b6cc2b5997979dc49ec089734714aff6c17bb7aa9fa02abc7c0a20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ironflow-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ipycanvas >=0.13.1
    - ipython >=7.21.0
    - ipywidgets >=7,<8
    - matplotlib-base >=3.6.0
    - nglview >=3.0.3
    - numpy >=1.23.3
    - pandas >=1.5.0
    - pyiron_base >=0.5.24
    - pyiron_atomistics >=0.2.58
    - pyiron_ontology >=0.1.1
    - pyiron_gui >=0.0.9
    - ryvencore ==0.3.1.1
    - seaborn >=0.11.2
    - traitlets >=5.2.1.post0
    - owlready2 >=0.40

test:
  imports:
    - ironflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/ironflow
  summary: ironflow - A visual scripting interface for pyiron.
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    ironflow combines ryven, ipycanvas and ipywidgets to provide a Jupyter-based visual scripting gui for building and 
    running pyiron workflow graphs.
  doc_url: https://pyiron.org
  dev_url: https://github.com/pyiron

extra:
  recipe-maintainers:
    - pyiron-runner
    - liamhuber
    - jan-janssen
