{% set name = "ironflow" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ironflow-{{ version }}.tar.gz
  sha256: bedce1794dec8556940eedef76a63551166d9761fb14d0a8870a8ca443588697
  patches:
    - versioneer.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - ipycanvas
    - ipython
    - ipywidgets >=7,<8
    - matplotlib-base
    - nglview
    - numpy
    - owlready2
    - pyiron_base
    - pyiron_atomistics
    - pyiron_gui >=0.0.8
    - pyiron_ontology >=0.1.3
    - ryvencore
    - seaborn
    - traitlets

test:
  imports:
    - ironflow
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pyiron/ironflow
  summary: ironflow - A visual scripting interface for pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - liamhuber
    - jan-janssen
