{% set python_min = '3.10' %}
{% set name = "ironflow" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ironflow-{{ version }}.tar.gz
  sha256: 4c6c223c46ac1b3409b985a358b10d1476583ebab7e1b28f05a7600401c75f85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - aimsgb =0.1.3
    - jupyterlab =3.6.7
    - pandas =1.5.3
    - pymatgen =2023.5.10
    - python >={{ python_min }},<3.12
    - ipycanvas =0.13.2
    - ipython =8.24.0
    - ipywidgets =7.7.1
    - matplotlib-base =3.8.4
    - nglview =3.0.8
    - numpy =1.26.4
    - owlready2 =0.46
    - pyiron_base =0.5.33
    - pyiron_atomistics =0.2.63
    - pyiron_gui =0.0.8
    - pyiron_ontology =0.1.3
    - ryvencore =0.3.1.1
    - seaborn =0.13.2
    - traitlets =5.14.3

test:
  imports:
    - ironflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/ironflow
  summary: ironflow - A visual scripting interface for pyiron.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pyiron-runner
    - liamhuber
    - jan-janssen
